### ISSUE TITLE
Could you remove ProjectSettings and Packages from .gitignore?

### ISSUE THREAD

**Issue by andybak** [arigo/LPVTest#1]
It makes it much harder for people to open the project successfully and removes any information about Unity versions

**Comment by arigo** [comment]
Added ProjectSettings.  Thanks for the note!

About Packages, there isn't anything useful in there for LPVTest, as far as I can tell.  I checked that you can successfully open a completely clean working copy (with ProjectSettings but not Packages).

**Comment by andybak** [comment]
Is there a good reason not to include packages? I can think of situations where it's absence might cause issues in the future but I can't think of any problems caused by including it.

1. It shouldn't be in .gitignore as any clones will inherit this .gitignore and might need version control of the packages dir.
2. Someone who clones this repo and opens the project in a newer version of Unity will get different default packages which might break things. If the packages dir was included then it would at least freeze their packages to the versions included in the version of Unity you used.

Why not just include it? 99% of other Unity repos on Github do.

**Comment by arigo** [comment]
Because I still don't see the point.  This repo is not like a game or some stand-alone thing.  It's a library you're supposed to use in your own projects, and it's certainly not supposed to depend on the exact set of packages you have.  It's also supposed to work on a range of Unity versions, though I didn't check more than one, so that's why I'm fine with adding ProjectSettings.  See for example https://github.com/arigo/shaderdebugger, which I actually tested on a range of Unity versions and project settings, so I didn't put ProjectSettings at all.
